# Generated by Django 4.1.3 on 2022-12-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='BaseItem',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('categlory', models.CharField(default='Item', max_length=128)),
				('name', models.CharField(max_length=128)),
				('description', models.CharField(max_length=1024)),
				('publisher', models.CharField(max_length=128)),
				('address', models.CharField(max_length=128)),
				('phone', models.CharField(max_length=128)),
				('email', models.EmailField(max_length=254)),
			],
		),
		migrations.CreateModel(
			name='Food',
			fields=[
				('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.baseitem')),
				('best_before', models.CharField(max_length=128)),
			],
			bases=('item.baseitem',),
		),
		migrations.CreateModel(
			name='Item',
			fields=[
				('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.baseitem')),
			],
			bases=('item.baseitem',),
		),
	]
