# Generated by Django 4.1.3 on 2022-12-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.baseitem')),
                ('author', models.CharField(max_length=1024)),
                ('ISBN', models.CharField(max_length=1024)),
                ('publish', models.CharField(max_length=1024)),
            ],
            bases=('item.baseitem',),
        ),
    ]
